export const SEARCH_BY_KEYWORD = "SEARCH_BY_KEYWORD"
export const SEARCH_BY_KEYWORD_LOADING = "SEARCH_BY_KEYWORD_LOADING"
export const SEARCH_BY_KEYWORD_SUCCESS = "SEARCH_BY_KEYWORD_SUCCESS"
export const SEARCH_BY_KEYWORD_ERROR = "SEARCH_BY_KEYWORD_ERROR"

export const SEARCH_BY_EXACT_KEYWORD = "SEARCH_BY_EXACT_KEYWORD"
export const SEARCH_BY_EXACT_KEYWORD_LOADING = "SEARCH_BY_EXACT_KEYWORD_LOADING"
export const SEARCH_BY_EXACT_KEYWORD_SUCCESS = "SEARCH_BY_EXACT_KEYWORD_SUCCESS"
export const SEARCH_BY_EXACT_KEYWORD_ERROR = "SEARCH_BY_EXACT_KEYWORD_ERROR"

export const ADD_NEW_WORD_CLEAR = "ADD_NEW_WORD_CLEAR"
export const ADD_NEW_WORD = "ADD_NEW_WORD"
export const ADD_NEW_WORD_SUCCESS = "ADD_NEW_WORD_SUCCESS"
export const GO_BACK_WORD_FORM = "GO_BACK_WORD_FORM"
export const ADD_NEW_WORD_ERROR = "ADD_NEW_WORD_ERROR"

export const CLOSE_SEARCH = "CLOSE_SEARCH"
export const OPEN_SEARCH = "OPEN_SEARCH"

export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const LOGOUT = "LOGOUT"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"


export const REGISTER = "REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_ERROR = "REGISTER_ERROR"

export const REGISTER_CLEAR = "REGISTER_CLEAR"
export const OPEN_AUTH_MODAL = "OPEN_AUTH_MODAL"
export const CLOSE_AUTH_MODAL = "CLOSE_AUTH_MODAL"
export const TOGGLE_AUTH_FORMS = "TOGGLE_AUTH_FORMS"

export const OPEN_WORDFORM_MODAL = "OPEN_WORDFORM_MODAL"
export const CLOSE_WORDFORM_MODAL = "CLOSE_WORDFORM_MODAL"

export const SEARCH_BY_ID = "SEARCH_BY_ID"
export const SEARCH_BY_ID_LOADING = "SEARCH_BY_ID_LOADING"
export const SEARCH_BY_ID_SUCCESS = "SEARCH_BY_ID_SUCCESS"
export const SEARCH_BY_ID_ERROR = "SEARCH_BY_ID_ERROR"

export const FETCH_WORDS = "FETCH_WORDS"
export const FETCH_WORDS_LOADING = "FETCH_WORDS_LOADING"
export const FETCH_WORDS_SUCCESS = "FETCH_WORDS_SUCCESS"
export const FETCH_WORDS_ERROR = "FETCH_WORDS_ERROR"

export const FETCH_BUCKETS = "FETCH_BUCKETS"
export const FETCH_BUCKETS_LOADING = "FETCH_BUCKETS_LOADING"
export const FETCH_BUCKETS_SUCCESS = "FETCH_BUCKETS_SUCCESS"
export const FETCH_BUCKETS_ERROR = "FETCH_BUCKETS_ERROR"

export const FETCH_BUCKETS_DETAILS = "FETCH_BUCKETS_DETAILS"
export const FETCH_BUCKETS_DETAILS_SUCCESS = "FETCH_BUCKETS_DETAILS_SUCCESS"
export const FETCH_BUCKETS_DETAILS_ERROR = "FETCH_BUCKETS_DETAILS_ERROR"

export const TOGGLE_VOCABULARY_PRACTICE = "TOGGLE_VOCABULARY_PRACTICE"
export const GET_TOKEN = "GET_TOKEN"

export const SAVE_BUCKET = "SAVE_BUCKET"
export const SAVE_BUCKET_SUCCESS = "SAVE_BUCKET_SUCCESS"
export const SAVE_BUCKET_ERROR = "SAVE_BUCKET_ERROR"


export const CATEGORIES =  [
    {key: 'all', value: 'all', text: 'Todas'},
    {key: 'Cuerpo humano', value: 'Cuerpo humano', text: 'Cuerpo humano'},
    {key: 'Animales', value: 'Animales', text: 'Animales'},
    {key: 'Citas', value: 'Citas', text: 'Citas'},
    {key: 'Doctor', value: 'Doctor', text: 'Doctor'},
    {key: 'Escuela', value: 'Escuela', text: 'Escuela'}
];

export const WORD_TYPES = [
    {key: 'all', value: 'all', text: 'Todas'},
    {key: 'verb', value: 'verb', text: 'Verbos'},
    {key: 'noun', value: 'noun', text: 'Sustantivos'}
]

export const ARTICLES = [
    {key: 'der', text: 'der', value: 'der'},
    {key: 'die', text: 'die', value: 'die'},
    {key: 'das', text: 'das', value: 'das'},
]

export const OPEN_BUCKET_MODAL = "OPEN_BUCKET_MODAL"
export const CLOSE_BUCKET_MODAL = "CLOSE_BUCKET_MODAL"

export const DELETE_BUCKET = "DELETE_BUCKET"
export const DELETE_BUCKET_SUCCESS = "DELETE_BUCKET_SUCCESS"
export const DELETE_BUCKET_ERROR = "DELETE_BUCKET_ERROR"
export const OPEN_DELETE_BUCKET_MODAL = "OPEN_DELETE_BUCKET_MODAL"
export const CLOSE_DELETE_BUCKET_MODAL = "CLOSE_DELETE_BUCKET_MODAL"

export const OPEN_SEND_TO_BUCKET_MODAL = "OPEN_SEND_TO_BUCKET_MODAL"
export const OPEN_SEND_TO_BUCKET_MODAL_SUCCESS = "OPEN_SEND_TO_BUCKET_MODAL_SUCCESS"
export const OPEN_SEND_TO_BUCKET_MODAL_ERROR = "OPEN_SEND_TO_BUCKET_MODAL_ERROR"
export const CLOSE_SEND_TO_BUCKET_MODAL = "CLOSE_SEND_TO_BUCKET_MODAL"

export const OPEN_DELETE_SENTENCE_MODAL = "OPEN_DELETE_SENTENCE_MODAL"
export const CLOSE_DELETE_SENTENCE_MODAL = "CLOSE_DELETE_SENTENCE_MODAL"

export const ADD_COMMENT = "ADD_COMMENT"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR"

export const EDIT_COMMENT = "EDIT_COMMENT"
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS"
export const EDIT_COMMENT_ERROR = "EDIT_COMMENT_ERROR"

export const DELETE_COMMENT = "DELETE_COMMENT"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR"


